base_config: "base_sac_adroit_sample_efficient.yml"
env:
  env_id: "AdroitHandPenSparse-v1"
  max_episode_steps: 100
eval_env:
  max_episode_steps: 100

train:
  dataset_path: "demos/d4rl-full/AdroitHandPenSparse-v1/trajectory.h5"