base_config: "base_sac_d4rl_sample_efficient.yml"
env:
  env_id: "AdroitHandDoorSparse-v1"
  max_episode_steps: 200
eval_env:
  max_episode_steps: 200

train:
  dataset_path: "demos/d4rl-full/AdroitHandDoorSparse-v1/trajectory.h5"